//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Xaml.Interactivity.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Xaml.Interactivity.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Category_Common_Properties {
            get {
                return ResourceManager.GetString("Category_Common_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Category_Name_Actions {
            get {
                return ResourceManager.GetString("Category_Name_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls a method on a specified object when invoked..
        /// </summary>
        internal static string Description_CallMethodAction {
            get {
                return ResourceManager.GetString("Description_CallMethodAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get or sets the name of the method to invoke..
        /// </summary>
        internal static string Description_CallMethodAction_MethodName {
            get {
                return ResourceManager.GetString("Description_CallMethodAction_MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the object that exposes the method..
        /// </summary>
        internal static string Description_CallMethodAction_TargetObject {
            get {
                return ResourceManager.GetString("Description_CallMethodAction_TargetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action that will change a specified property to a specified value when invoked..
        /// </summary>
        internal static string Description_ChangePropertyAction {
            get {
                return ResourceManager.GetString("Description_ChangePropertyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the property to change..
        /// </summary>
        internal static string Description_ChangePropertyAction_PropertyName {
            get {
                return ResourceManager.GetString("Description_ChangePropertyAction_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the object whose property will be changed..
        /// </summary>
        internal static string Description_ChangePropertyAction_TargetObject {
            get {
                return ResourceManager.GetString("Description_ChangePropertyAction_TargetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the value to set..
        /// </summary>
        internal static string Description_ChangePropertyAction_Value {
            get {
                return ResourceManager.GetString("Description_ChangePropertyAction_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action that will change the state of the specified Storyboard when executed..
        /// </summary>
        internal static string Description_ControlStoryboardAction {
            get {
                return ResourceManager.GetString("Description_ControlStoryboardAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the action to execute on the Storyboard..
        /// </summary>
        internal static string Description_ControlStoryboardAction_ControlStoryboardOption {
            get {
                return ResourceManager.GetString("Description_ControlStoryboardAction_ControlStoryboardOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the targeted Storyboard..
        /// </summary>
        internal static string Description_ControlStoryboardAction_Storyboard {
            get {
                return ResourceManager.GetString("Description_ControlStoryboardAction_Storyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A behavior that performs actions when the bound data meets a specified condition..
        /// </summary>
        internal static string Description_DataTriggerBehavior {
            get {
                return ResourceManager.GetString("Description_DataTriggerBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the collection of actions associated with the behavior..
        /// </summary>
        internal static string Description_DataTriggerBehavior_Actions {
            get {
                return ResourceManager.GetString("Description_DataTriggerBehavior_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the bound object that the DataTriggerBehavior will listen to..
        /// </summary>
        internal static string Description_DataTriggerBehavior_Binding {
            get {
                return ResourceManager.GetString("Description_DataTriggerBehavior_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the type of comparison to be performed between Binding and Value..
        /// </summary>
        internal static string Description_DataTriggerBehavior_ComparisonCondition {
            get {
                return ResourceManager.GetString("Description_DataTriggerBehavior_ComparisonCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the value to be compared with the value of Binding..
        /// </summary>
        internal static string Description_DataTriggerBehavior_Value {
            get {
                return ResourceManager.GetString("Description_DataTriggerBehavior_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A behavior that listens for a specified event on its source and executes its actions when that event is fired..
        /// </summary>
        internal static string Description_EventTriggerBehavior {
            get {
                return ResourceManager.GetString("Description_EventTriggerBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the collection of actions associated with the behavior..
        /// </summary>
        internal static string Description_EventTriggerBehavior_Actions {
            get {
                return ResourceManager.GetString("Description_EventTriggerBehavior_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the event to listen for..
        /// </summary>
        internal static string Description_EventTriggerBehavior_EventName {
            get {
                return ResourceManager.GetString("Description_EventTriggerBehavior_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the source object from which this behavior listens for events. If SourceObject is not set, the source will default to AssociatedObject..
        /// </summary>
        internal static string Description_EventTriggerBehavior_SourceObject {
            get {
                return ResourceManager.GetString("Description_EventTriggerBehavior_SourceObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action that will transition a FrameworkElement to a specified VisualState when executed..
        /// </summary>
        internal static string Description_GoToStateAction {
            get {
                return ResourceManager.GetString("Description_GoToStateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name of the VisualState..
        /// </summary>
        internal static string Description_GoToStateAction_StateName {
            get {
                return ResourceManager.GetString("Description_GoToStateAction_StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the target object..
        /// </summary>
        internal static string Description_GoToStateAction_TargetObject {
            get {
                return ResourceManager.GetString("Description_GoToStateAction_TargetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets whether or not to use a VisualTransition to transition between states..
        /// </summary>
        internal static string Description_GoToStateAction_UseTransitions {
            get {
                return ResourceManager.GetString("Description_GoToStateAction_UseTransitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A behavior that allows incremental updating of ListView and GridView contents to support faster updating. By attaching this behavior to elements in the ItemTemplate used by these views, some of the updates can be deferred until there is render time available, resulting in a smoother experience..
        /// </summary>
        internal static string Description_IncrementalUpdateBehavior {
            get {
                return ResourceManager.GetString("Description_IncrementalUpdateBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the relative priority of this incremental update. Lower Phase values are addressed first..
        /// </summary>
        internal static string Description_IncrementalUpdateBehavior_Phase {
            get {
                return ResourceManager.GetString("Description_IncrementalUpdateBehavior_Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes a specified ICommand when invoked..
        /// </summary>
        internal static string Description_InvokeCommandAction {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the command the action should invoke..
        /// </summary>
        internal static string Description_InvokeCommandAction_Command {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the parameter that is passed to ICommand.Execute. If this is not set, the parameter from the InvokeCommandAction.Execute method will be used..
        /// </summary>
        internal static string Description_InvokeCommandAction_CommandParameter {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction_CommandParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the converter that is run on the parameter of the InvokeCommandAction.Execute method..
        /// </summary>
        internal static string Description_InvokeCommandAction_InputConverter {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction_InputConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the language that is passed to the IValueConverter.Convert method of InputConverter..
        /// </summary>
        internal static string Description_InvokeCommandAction_InputConverterLanguage {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction_InputConverterLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the parameter that is passed to the IValueConverter.Convert method of InputConverter..
        /// </summary>
        internal static string Description_InvokeCommandAction_InputConverterParameter {
            get {
                return ResourceManager.GetString("Description_InvokeCommandAction_InputConverterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action that switches the current visual to the specified Page..
        /// </summary>
        internal static string Description_NavigateToPageAction {
            get {
                return ResourceManager.GetString("Description_NavigateToPageAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the parameter that will be passed to the Frame.Navigate method..
        /// </summary>
        internal static string Description_NavigateToPageAction_Parameter {
            get {
                return ResourceManager.GetString("Description_NavigateToPageAction_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the fully qualified name of the Page to navigate to..
        /// </summary>
        internal static string Description_NavigateToPageAction_TargetPage {
            get {
                return ResourceManager.GetString("Description_NavigateToPageAction_TargetPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action that will play a sound to completion..
        /// </summary>
        internal static string Description_PlaySoundAction {
            get {
                return ResourceManager.GetString("Description_PlaySoundAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the location of the sound file..
        /// </summary>
        internal static string Description_PlaySoundAction_Source {
            get {
                return ResourceManager.GetString("Description_PlaySoundAction_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or set the volume of the sound..
        /// </summary>
        internal static string Description_PlaySoundAction_Volume {
            get {
                return ResourceManager.GetString("Description_PlaySoundAction_Volume", resourceCulture);
            }
        }
    }
}
