name: Build Managed

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  managed-build:
    runs-on: windows-latest
    steps:
    - name: Checkout XamlBehaviors.git 
      uses: actions/checkout@v3

    - name: Install the .NET 8.0.400 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.400

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup/Install NuGet 6.11.0
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: '6.11.0'

    - name: NuGet Restore BehaviorsSDKManaged.sln
      run: nuget restore src\BehaviorsSDKManaged\BehaviorsSDKManaged.sln

    - name: Build BehaviorsSDKManaged.sln
      run: msbuild src\BehaviorsSDKManaged\BehaviorsSDKManaged.sln /p:Configuration=Release

    - name: Run Tests
      run: dotnet test src\BehaviorsSDKManaged\ManagedUnitTests\ManagedUnitTests.csproj
