name: Build Managed

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  managed-build:
    runs-on: windows-2022
    steps:
    - name: Checkout XamlBehaviors.git 
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install the .NET 9.0.x SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

    - name: Setup/Install NuGet 6.11.0
      uses: nuget/setup-nuget@b26b823c478ee115be5c9403e62c90b0bf943843 # v3.1.0
      with:
        nuget-version: '6.11.0'

    - name: NuGet Restore BehaviorsSDKManaged.sln
      run: nuget restore src\BehaviorsSDKManaged\BehaviorsSDKManaged.sln

    - name: Build BehaviorsSDKManaged.sln
      run: msbuild src\BehaviorsSDKManaged\BehaviorsSDKManaged.sln /p:Configuration=Release -v:diag /bl
    
    - name: Upload MSBuild binary log
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: msbuild_binlog_Release_x64
        path: msbuild.binlog
        if-no-files-found: error
    
    - name: Build UWP package
      run: msbuild /t:pack src\BehaviorsSDKManaged\Microsoft.Xaml.Interactivity.Uwp\Microsoft.Xaml.Interactivity.Uwp.csproj /p:Configuration=Release /p:TimestampPackage=true
    
    - name: Build WinUI 3 package
      run: msbuild /t:pack src\BehaviorsSDKManaged\Microsoft.Xaml.Interactivity.WinUI\Microsoft.Xaml.Interactivity.WinUI.csproj /p:Configuration=Release /p:TimestampPackage=true
    
    - name: Upload NuGet packages
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: nuget_packages
        path: out\NuGetPackages\*.nupkg
        if-no-files-found: error

  samples-build:
    runs-on: windows-2022
    steps:
    - name: Checkout XamlBehaviors.git 
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Install the .NET 9.0.x SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

    - name: Setup/Install NuGet 6.11.0
      uses: nuget/setup-nuget@b26b823c478ee115be5c9403e62c90b0bf943843 # v3.1.0
      with:
        nuget-version: '6.11.0'

    - name: NuGet Restore XAMLBehaviorsSample.sln
      run: nuget restore samples\CS\XAMLBehaviorsSample.sln
      
    - name: Build XAMLBehaviorsSample.sln
      run: msbuild samples\CS\XAMLBehaviorsSample.sln /p:Configuration=Release -v:diag /bl
    
    - name: Upload MSBuild binary log
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: msbuild_samples_binlog_Release_x64
        path: msbuild.binlog
        if-no-files-found: error
